// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWizardAPI.Data;

#nullable disable

namespace MovieWizardAPI.Migrations.MovieRevenueDb
{
    [DbContext(typeof(MovieRevenueDbContext))]
    partial class MovieRevenueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieWizardAPI.Models.MovieRevenue", b =>
                {
                    b.Property<int>("MovieRevenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieRevenueId"), 1L, 1);

                    b.Property<decimal>("RevenueAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RevenueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("MovieRevenueId");

                    b.ToTable("MovieRevenues", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
